export const GET_AR_BALANCE_REQUEST = 'GET_AR_BALANCE_REQUEST'
export const SET_AR_BALANCE_REQUEST = 'SET_AR_BALANCE_REQUEST'
export const SET_AR_BALANCE_REQUEST_ERROR = 'SET_AR_BALANCE_REQUEST_ERROR'